### ISSUE TITLE
Missed libgadu.h file

### ISSUE THREAD

**Issue by Rudzix77** [mpapierski/node-gadu#1]
Hi! 
There is a problem with installing this module. nom returns me this error:

  CXX(target) Release/obj.target/gadu/src/gadu.o
../src/gadu.cc:3:10: fatal error: 'libgadu.h' file not found
# include "libgadu.h"

**Comment by mpapierski** [comment]
Do you have libgadu library installed? binding.gyp does not make any assumption for the libgadu.h header location. If you install libgadu into /usr or /usr/local everything works fine.

Another solution might be to bundle the libgadu library with the node-gadu package. But that will require libgadu building script to fit inside .gyp.
