### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by tomekb530** [mpapierski/node-gadu#2]
When i am using npm install gadu i have error with node-gyp rebuild

**Comment by mpapierski** [comment]
Can you please post your error log? This might have something to do with changes in v8 APIs, but its just a guess.

**Comment by tomekb530** [comment]
http://tomekk.pl/nodegadu.txt Here you are :) Hope you will repair it ;)

**Comment by mpapierski** [comment]
Check out #3. Once merged it should solve your problem.

Thanks!

**Comment by mpapierski** [comment]
PR #3 is successfuly merged. Please try again. If the problem remains please consider opening new issue.
