### ISSUE TITLE
Update node-gadu on npmjs.com

### ISSUE THREAD

**Issue by marcin-uliasz** [mpapierski/node-gadu#4]
Hi, I created this issue to suggest you to update the version of node-gadu on npmjs.org as well, so that when you do _npm install node-gadu_, version 0.0.3 will be picked up and not 0.0.2 as it is at the moment.

**Comment by mpapierski** [comment]
Good idea! Looks like this could be automated on travis-ci. This sounds easy to do: https://docs.travis-ci.com/user/deployment/npm/. I'll try to do it.

**Comment by mpapierski** [comment]
Solved in c8b1991a908d3a1c14e67e2b6245d7a4ea96b4cf. From now on each new tag will be automatically deployed on npmjs.

**Comment by mpapierski** [comment]
(try updating node-gadu to `0.1.2` through npm)
